name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master  # use 'main' if that's your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          REPO="https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}"

          # Create a temp dir for gh-pages branch
          mkdir gh-pages
          cd gh-pages
          git init
          git remote add origin "$REPO"

          # Create or switch to gh-pages branch
          git checkout -b gh-pages

          # Copy build files
          cp -r ../build/* .

          # Commit and push
          git add .
          git commit -m "Deploy React App to GitHub Pages - ${{ github.sha }}"
          git push origin gh-pages --force
